
spring:
  profiles:
    active: development
  main:
    banner-mode: "off"

# 关闭Spring boot艺术字： spring.main.banner-mode=off


tobao:
  associateId: haha-20

# 启用和禁用端点
#endpoints:

management:
  endpoints:
    web:
      exposure:
        include: info,health
#        beans,conditions,env,mappings,metrics,trace

info:
  ReadingList:
    email: hefrankeleyn@gmail.com
    phone: 123123123
---
spring:
  profiles: development
# 开发环境下关闭缓存
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/Documents/opt/servers/h2databases/spittr
    username: spittr
    password: spittr
  jpa:
    hibernate:
      ddl-auto: none
# 修改服务器端口

#server:
#  port: 8000
#  ssl:
#    # 使服务器提供HTTPS服务
#    key-store: file:///Users/lifei/innertomcatkeys.jks
#    key-store-password: wordpass
#    key-password: wordpass

#logging:
  # 修改将日志写的地方
#  path: /Users/lifei/Documents/opt/logs/
#   path和file不能同时使用，否则只有file生效
#  file: ReadingList.log
  #修改日志的级别
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
---
spring:
  profiles: production

# 生产环境下开启缓存
  thymeleaf:
    cache: true
---

